# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.1
maven_group = net.klayil.veggycraft
archives_name = veggycraft
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.10

# Yarn & Others
parchment_version_minecraft = 1.21.10

yarn_mappings = 1.21.10+build.1

yarn_mappings_patch_neoforge_version = 1.21+build.4

# Dependencies
architectury_api_version = 18.0.8
# ^^ 18.0.6 ^^

fabric_loader_version = 0.18.1
fabric_api_version = 0.138.3+1.21.10

neoforge_version = 21.10.37-beta
# ^^ 21.10.1-beta ^^

jei_version = 26.1.0.7
appleskin_version=mc1.21.9-3.0.7
cloth_config_version=20.0.149
balm_version=21.10.1+1.21.10
rei_version = 21.9.812
klay_api_version = 0.0.7
